### ISSUE TITLE
Where do LDP-NR subject triples go?

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp-archive/trellis-constraint-rules#3]
Given:
> Single-subject rule -- RDF graphs must have a single subject, corresponding to the resource URI (hashURIs are allowed)

where are triples _about_ LDP-NRs housed?

**Comment by acoburn** [comment]
My interpretation of `Link: <some-ldp-nr>; rel="describes"` is that any triples on the LDP-RS (as a consequence of the `Link` header) describe the LDP-NR. Absent that `Link` header, those triples would only be describing the LDP-RS itself.

**Comment by ajs6f** [comment]
The question is, what is the subject of those triples? If the LDP-RS, then they clearly do _not_ describe the LDP-NR. If the LDP-NR, they violate the rule quoted above.

**Comment by acoburn** [comment]
No, the subject is the LDP-RS, and as described above, via the `Link` header, they (by definition) also describe the LDP-NR.

**Comment by ajs6f** [comment]
That is nonsensical to me. You are saying that a triple of the form:
```
<foo> hasWidth 3567^^uom:pixels .
```
secretly means:
```
<bar> hasWidth 3567^^uom:pixels .
```
because of an HTTP header elsewhere in the world? How on earth can that be interpreted as RDF?

**Comment by acoburn** [comment]
fine, add an owl:sameAs triple in there. The other approach: making the subject of the LDP-RS be the LDP-NR is nonsensical to me.

**Comment by ajs6f** [comment]
An `owl:sameAs` triple?! How can (say) an image be the same thing as an RDF graph?

**Comment by acoburn** [comment]
Then we just disagree on this. But unless this actually violates the LDP or Fedora specs, I'll keep this approach.

**Comment by ajs6f** [comment]
I think it violates RDF itself, but I'm not going to berate you about it. I'm increasingly convinced that the single-subject rule and the notion of standoff description cannot be reconciled directly. A new approach must be found.

**Comment by acoburn** [comment]
Another approach would be to use hashURIs. I would need to think a bit more about the implications of that, but you could, for instance, have the LDP-NR at `http://example.org/resource` and the LDP-RS at `http://example.org/resource#description`. You'd then use `Accept` headers to request the different representations.

**Comment by ajs6f** [comment]
Yes, this is where I think we're going to have to go. I need to think about that plays out with multiple descriptions.

**Comment by ajs6f** [comment]
Yes, this is where I think we're going to have to go. I need to think about that plays out with multiple descriptions.

**Comment by acoburn** [comment]
You could use an opaque hashURI (which is what I'd use anyway). This would allow multiple descriptions. The server response would contain all such descriptions, since the HTTP spec mandates that a server ignores any URL fragment in a request, but the data would be available for any client processing.

**Comment by ajs6f** [comment]
Also there is the question of how you describe an RDF resource. @barmintor is interested in that, I think, and @no-reply frequently raised it as a use case from DPLA. I am interested in that case because a lot of bioinformatics work can be expressed in RDF.

**Comment by acoburn** [comment]
Named graphs?

**Comment by ajs6f** [comment]
By "opaque" do you imply "server-generated" (to avoid collisions)?

I think what we're playing with is the following move: we've been treating description/described-by purely as a relationship. We might instead think of description as a particular kind of _representation_.

**Comment by ajs6f** [comment]
Maybe named graphs. I'm frightened by the thought, but maybe we want the resource retrieved at an URI to be, not a graph, but a dataset (in the full RDF sense of that term).

**Comment by acoburn** [comment]
yes, by opaque, I mean server-generated. And the way I've been designing trellis is that, internally, a LDP-NR and the describing LDP-RS is actually a single (internal) resource with different representations (and also different URIs -- though hashURIs may make that considerably easier).

**Comment by ajs6f** [comment]
I'm reading [the relevant bits](https://www.w3.org/TR/ldp/#ldprs) and I can't see why you couldn't return a dataset for an LDP-RS (instead of a simple graph).

**Comment by acoburn** [comment]
That may, in fact, be the best path forward.

**Comment by ajs6f** [comment]
Well, as said above and discussed elsewhere, the question really is whether to commit to an epistemology in which description is a form of representation. If you do that, you open up all this other stuff about hash-URIs and datasets. If you don't, (I believe) you have to face the fact that the single-subject rule is fundamentally in conflict with description-as-relationship, and you find some least-worst way to deal with that.

**Comment by acoburn** [comment]
Closing this, as it seems we have a path forward with the use of hashURIs and RDF datasets.
